# Use Python 3.10 as a parent image
FROM python:3.10-slim
ENV PYTHONPATH /app:$PYTHONPATH
# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Poetry and dependencies
RUN apt-get update && apt-get install -y iputils-ping \
    && pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-root \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# By default, run pytest to execute the tests
CMD ["poetry", "run", "pytest", "-v"]
