name: Linting and Code Formatting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort

    - name: Run Black
      run: |
        black .

    - name: Check import order with isort
      run: |
        isort .

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automatically fix code style issues" && git push)
