name: Linting and Code Formatting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort

    - name: Run Black
      run: |
        black --check .

    - name: Check import order with isort
      run: |
        isort --check-only --diff .
